### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by sdebruyn** [crowdsecurity/cs-nginx-bouncer#22]
Nginx is most often deployed as a Docker image, so it would make sense that this bouncer would be compatible with that. Maybe an image built on top of the official nginx image?

**Comment by he2ss** [comment]
Hi @sdebruyn,

We already did the same with https://github.com/crowdsecurity/cs-openresty-bouncer, but we'll not release new image in every openresty new image version. Maintaining nginx versions will be painfull for us.
We can have nginx docker image but we'll release new image version every release on the bouncer not on nginx version until some ask for it etc, it will not be automatically done.
I think it's better if you build you docker image because you'll have custom config and then you can add the bouncer. 

So what do you think about that ?

**Comment by LaurenceJJones** [comment]
Closing issue, TLDR: we will not maintain a nginx image since users will want to inject there own custom confs

If you dont agree with the answer please reopen
